# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0b1426335c5609d3cd44f143a029a7c"
name = "furniture-ai"
application_url = "https://aifurniture.app/shopify"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://aifurniture.app/api/shopify/webhooks"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://aifurniture.app/api/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://aifurniture.app/auth/callback" ]
