# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0b1426335c5609d3cd44f143a029a7c"
name = "furniture-ai"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
